## terminal 1
kienndt@ubuntu:~/Documents/Projects/udacity-project4_udacity_aws_devops$ ./run_kubernetes.sh 
pod/devops4 created
NAME      READY   STATUS              RESTARTS   AGE
devops4   0/1     ContainerCreating   0          0s
error: unable to forward port because pod is not running. Current status=Pending
kienndt@ubuntu:~/Documents/Projects/udacity-project4_udacity_aws_devops$ ./run_kubernetes.sh 
Error from server (AlreadyExists): pods "devops4" already exists
NAME      READY   STATUS    RESTARTS   AGE
devops4   1/1     Running   0          24s
Forwarding from 127.0.0.1:8000 -> 80
Forwarding from [::1]:8000 -> 80
Handling connection for 8000

## terminal 2
kienndt@ubuntu:~/Documents/Projects/udacity-project4_udacity_aws_devops$ kubectl logs devops4
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 129-516-115
[2022-12-31 12:26:19,623] INFO in app: JSON payload: 
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2022-12-31 12:26:19,630] INFO in app: Inference payload DataFrame: 
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2022-12-31 12:26:19,636] INFO in app: Scaling Payload: 
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2022-12-31 12:26:19,638] INFO in app: Prediction: 
[20.35373177134412]
127.0.0.1 - - [31/Dec/2022 12:26:19] "POST /predict HTTP/1.1" 200 -